---
abstract: 'Install and execute CPAN package binaries'
author:
  - 'Thibault Duponchelle <thibault.duponchelle@gmail.com>'
build_requires:
  App::cpm: '0'
  IO::Socket::SSL: '1.42'
  Search::Elasticsearch: '0'
  Search::Elasticsearch::Client::2_0::Direct: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-cpx
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006'
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
